# Generated by Django 3.1.3 on 2020-11-30 18:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Surname', models.CharField(max_length=50)),
                ('Fathername', models.CharField(max_length=50)),
                ('Date_of_birth', models.DateTimeField(default=django.utils.timezone.now)),
                ('Passport_series', models.IntegerField()),
                ('Passport_number', models.IntegerField()),
                ('Address', models.CharField(max_length=300)),
                ('Phone_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Imychestvo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(help_text='Введите название имущества', max_length=200, null=True)),
                ('Description', models.TextField()),
                ('Type_of_property', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_contract', models.CharField(help_text='Введите название имущества', max_length=200, null=True)),
                ('Sum', models.IntegerField()),
                ('Revenue_contract', models.IntegerField()),
                ('text', models.TextField()),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.client')),
                ('imychestvo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.imychestvo')),
            ],
        ),
    ]
