# Generated by Django 3.1.3 on 2020-11-30 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='Name_contract',
            field=models.CharField(help_text='Введите название договора', max_length=200, null=True),
        ),
    ]
